cgen/urls.py
from django.conf.urls import patterns, url, include
from cgen.api import register_api


from cgen import views

urlpatterns = patterns('',
        url(r'^$', views.index, name='index'),
        url(r'^(?P<cid>\d+)/$', views.detail, name='detail'),
        url(r'^new/$', views.new, name='new'),
        url(r'^(?P<cid>\d+)/delete$', views.delete, name='delete'),
        url(r'^(?P<cid>\d+)/save/$', views.save, name='save'),
        url(r'^api/', include(register_api().urls), name='api'),
)

legendgen/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'legendgen.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^cgen/', include('cgen.urls', namespace="cgen")),
)

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns += staticfiles_urlpatterns()

cgen/models.py
from django.db import models

ATT_VALUES = (
        ('STR', 'Strength'),
        ('CON', 'Constitution'),
        ('DEX', 'Dexterity'),
        ('INT', 'Intelligence'),
        ('WIS', 'Wisdom'),
        ('CHA', 'Charisma'),
)

SIZE_VALUES = (
        ('S', 'Small'),
        ('M', 'Medium'),
        ('L', 'Large'),
)


class ClassChassis(models.Model):
    BAB_VALUES = (
        ('G', 'Good'),
        ('P', 'Poor'),
    )

    name = models.CharField(max_length=200)
    hp_per_level = models.SmallIntegerField(default=0)
    base_attack_bonus = models.CharField(max_length=1, choices=BAB_VALUES, default='P')
    kom = models.CharField(max_length=3, choices=ATT_VALUES, default='STR')
    kdm = models.CharField(max_length=3, choices=ATT_VALUES, default='STR')
    num_skills = models.SmallIntegerField(default=0)

    def __str__(self):
        return self.name


class Race(models.Model):
    name = models.CharField(max_length=200)
    size = models.CharField(max_length=1, choices=SIZE_VALUES, default='M')

    def __str__(self):
        return self.name


class Character(models.Model):
    cname = models.CharField(max_length=200)
    pname = models.CharField(max_length=200)
    class_chassis = models.ForeignKey(ClassChassis)
    race = models.ForeignKey(Race)

    str = models.SmallIntegerField(default=10)
    con = models.SmallIntegerField(default=10)
    dex = models.SmallIntegerField(default=10)
    int = models.SmallIntegerField(default=10)
    wis = models.SmallIntegerField(default=10)
    cha = models.SmallIntegerField(default=10)

    def __str__(self):
        return self.cname

cgen/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.core.urlresolvers import reverse
from django.core import serializers
import json

from collections import OrderedDict

from cgen.models import Character, ClassChassis, Race, ATT_VALUES


def index(request):
    clist = Character.objects.all()
    context = {'char_list': clist}
    return render(request, 'cgen/index.html', context)

def detail(request, cid):
    char = get_object_or_404(Character, pk=cid)
    attribs = OrderedDict()
    for i in ATT_VALUES:
        attribs[i[0].lower()] = (i[1], getattr(char, i[0].lower()))
    return render(request, 'cgen/detail.html', {
		'char': char,
		'classes': ClassChassis.objects.all(),
        'races': Race.objects.all(),
		'attribs': attribs,
	})

def new(request):
    char = Character(class_chassis=ClassChassis.objects.all()[:1].get(),
                     race=Race.objects.all()[:1].get())
    char.save()
    return HttpResponseRedirect(reverse('cgen:detail', args=(char.id,)))

def delete(request, cid):
    char = get_object_or_404(Character, pk=cid)
    char.delete()

    return HttpResponseRedirect(reverse('cgen:index'))

def save(request, cid):
    char = get_object_or_404(Character, pk=cid)

    # Details
    char.cname = request.POST['cname']
    char.pname = request.POST['pname']
    try:
        class_chassis = ClassChassis.objects.get(pk=request.POST['class_chassis'])
    except (KeyError, ClassChassis.DoesNotExist):
        return render(request, 'cgen/detail.html', {
            'char': char,
            'classes': ClassChassis.objects.all(),
            'error_message': "Invalid class chassis.",
        })

    char.class_chassis = class_chassis

    # Attributes
    for i in [i[0].lower() for i in ATT_VALUES]:
        setattr(char, i, request.POST[i])

    char.save()

    return HttpResponseRedirect(reverse('cgen:detail', args=(char.id,)))

cgen/templates/cgen/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>LegendGen</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
	</head>
	
	<body>
		<div class="container">
		{% block content %}
		{% endblock %}
		</div>
	
		<script src="https://code.jquery.com/jquery.js"></script>
		<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
		{% block script %}
		{% endblock %}
	</body>
</html>

cgen/templates/cgen/detail.html
{% extends "cgen/base.html" %}
{% block content %}
<h1>Edit Character</h1>

<ul class="nav nav-tabs">
	<li class="active"><a href="#detail" data-toggle="tab">Details</a></li>
	<li><a href="#todo" data-toggle="tab">Tracks</a></li>
	<li><a href="#todo" data-toggle="tab">Feats</a></li>
	<li><a href="#todo" data-toggle="tab">Items</a></li>
</ul>
{% if error_message %}<p class="alert alert-danger">{{ error_message }}</p>{% endif %}
		
<form class="form-horizontal" role="form" action="{% url 'cgen:save' char.id %}" method="post">
	{% csrf_token %}

	<div class="tab-content well">
		<div id="detail" class="tab-pane fade in active">
            <h2>Name</h2>
			<div class="form-group">
				<label for="cname">Character Name</label>
				<input type="text" class="form-control" id="cname" name="cname" value="{{char.cname}}">
			</div>
			<div class="form-group">
				<label for="pname">Player Name</label>
				<input type="text" class="form-control" id="pname" name="pname" value="{{char.pname}}">
			</div>

            <h2>Race</h2>
            <div class="form-group">
                <label for="race" class="sr-only">Race</label>
                <select class="form-control" name="race" id="race">
					{% for race in races%}
					<option value="{{race.id}}" {% if race.id == char.race.id %} selected {% endif %}>{{race}}</option>
					{% endfor %}
				</select>
            </div>
            <p>
               Size: <span id="race-size">{{char.race.get_size_display}}</span>
            </p>

            <h2>Class</h2>
			<div class="form-group">
				<label for="class_chassis" class="sr-only">Class Chassis</label>
				<select class="form-control" name="class_chassis" id="class_chassis">
					{% for cc in classes %}
					<option value="{{cc.id}}" {% if cc.id == char.class_chassis.id %} selected {% endif %}>{{cc}}</option>
					{% endfor %}
				</select>
			</div>
            <div class="form-group">
                <label for="kdm" class="control-label">KDM:</label>
                <span class="form-control-static" id="kdm">{{char.class_chassis.kdm}}</span>
            </div>
            <div class="form-group">
                <label for="kom" class="control-label">KOM:</label>
                <span class="form-control-static" id="kom">{{char.class_chassis.kom}}</span>
            </div>

            <h2>Attributes</h2>
			{% for k, v in attribs.items %}
			<div class="form-group">
				<label for="{{k}}" class="col-sm-2 control-label">{{v.0}}</label>
				<div class="col-xs-2">
					<input type="number" class="form-control att-input" id="{{k}}" name="{{k}}" value="{{v.1}}">
				</div>
				<div class="col-xs-2">
					(<span id="{{k}}mod"></span>)
				</div>
			</div>
			{% endfor %}
		</div>

		<div id="todo" class="tab-pane fade">
			<p class="alert alert-danger">Todo</p>
		</div>
	</div>

	<button type="submit" class="btn btn-primary">Save</button>
	<a href="{% url 'cgen:index' %}" class="btn btn-default">Character List</a>
	<a href="{% url 'cgen:delete' char.id %}" class="btn btn-danger">Delete</a>
</form>
{% endblock %}

{% block script %}
<script>
	$(document).ready(function() {
		update_attr_mod_func = function() {
			var modifier = ~~(($(this).val() - 10) / 2);
			$('#' + $(this).attr('name') + 'mod').text(((modifier >= 0) ? "+" : "") + modifier);
		};

		$('.att-input').each(update_attr_mod_func);
		$('.att-input').change(update_attr_mod_func);

		$('#race').change(function() {
		    $.ajax({
		        url: "{% url 'cgen:api_dispatch_list' api_name='v1' resource_name='race' %}" + $('#race option:selected').attr('value') + "/?format=json",
		        dataType: "json"
		    }).done(function(msg) {
		        $('#race-size').text(msg.size);
		    })
		});

		$('#class_chassis').change(function() {
            $.ajax({
                url: "{% url 'cgen:api_dispatch_list' api_name='v1' resource_name='classchassis' %}" + $('#class_chassis option:selected').attr('value') + "/?format=json",
                dataType: "json"
            }).done(function(msg) {
                $('#kdm').text(msg.kdm);
                $('#kom').text(msg.kom);
            })
		});
	});
</script>
{% endblock %}

cgen/templates/cgen/index.html
{% extends "cgen/base.html" %}

{% block content %}
	<h1>Characters</h1>
	
	{% if char_list %}
		<div class="list-group">
		{% for char in char_list %}
			<a class="list-group-item" href="{% url 'cgen:detail' char.id %}">{{char.cname}}</a></li>
		{% endfor %}
		</div>
	{% else %}
		<p>No characters are available.</p>
	{% endif %}

	<a href="{% url 'cgen:new' %}" class="btn btn-primary">Create New Character</a>
{% endblock %}